version: '2'
services:
 zookeeper:
   container_name: zookeeper
   image: wurstmeister/zookeeper:latest
   ports:
     - "2181:2181"
     - "2822:22"
     - "2888:2888"
     - "3888:3888"
   expose:
     - "2181"
     - "22"
     - "2888"
     - "3888"
   mem_limit: 1024m
   memswap_limit: 1024m
 kafka:
   container_name: kafka
   image: wurstmeister/kafka:latest
   ports:
     - "9092:9092"
   mem_limit: 1024m
   memswap_limit: 1024m
   environment:
     KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_HEAP_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms256M -Xmx768M"
     KAFKA_ADVERTISED_HOST_NAME: localhost